---
title: "Alternate EDE application for camera trap modeling"
output: pdf_document
---

NOTES:

-   When subbing the TDST stay time data for collar data summaries (i.e., only use count data without any camera trap stay time data), the prior sds on kappa must be small to let the model fit to the priors. Also, the priors do not need to be exactly the staying time but the proportion of time spent in each habitat type

-   I can't figure out how to translate cell-size staying time to camera viewshed-size staying time. Multiplying by camera area over cell area doesn't seem to work (oddly enough, this scaling works for counts...). Again, this doesn't pose a problem for the TDST when stay time data are omitted, but is useless when staying time data (from cameras) are used.

-   The habitat PR model works just as well as the TDST prior-no data model (I think they are pretty much equivalent). When fitting the habitat PR model with 0 cameras placed in a habitat type, the habitat-specific camera count must be set to 0, otherwise the uninformed priors on the 0-camera habitat types will run wild.

-   We need to think about how to estimate sds from habitat-specific staying time collected from collars. Currently, the habitat PR model does not use any SD and the TDST with priors-no data has a forced small prior variance. Maybe ask Dan and Ian the best way to incorporate this with the camera model.

This document breaks down the EDE to accommodate camera trap data, creating a model that allows for biased sample designs in non-homogeneous landscapes. Specifically, we require relative space use of animals to weigh density estimates of classified landscapes.

First, the equilibrium solution of the EDE assumes that animal densities are proportional to animal movement speeds, or staying time. The underlying equation describing the EDE is $$\frac{d_q}{\sum{d_q}} = \frac{\phi_q}{\sum{\phi_q}},$$ where $d_q$ is a density at location $q$ and $\phi_q$ is the staying time at location $q$. We interpret this equation to camera trap methodology in two ways: 1) cameras are placed only in one habitat type, and 2) cameras are placed across multiple habitat types.

Typically, camera traps estimate population densities that are use to calculate total abundances. The underlying formula to calculate abundances is $$N = \frac{\lambda A}{V T},$$ where $\lambda$ is the density, $A$ is the area of the habitat, $V$ is the camera viewshed area, and $T$ is the sampling period.

We can generalize the EDE by describing densities and staying time by habitat type rather than location, which can be defined as $d_h$ and $\phi_h$ for habitat type $h$. Then, we collect habitat-type specific staying times across the landscape with collared (GPS) data. For example, with a collared data set, we find that animals on average spend 50% of time in forested area, 35% on grassland, and 15% on road. With this information, we now know, for example, that road densities should be about 15% of total densities. We can use this to calculate total abundances as follows.

Habitat-specific abundances can be calculated by multiplying density by the area of the habitat, $$N_h = \frac{\lambda_h A}{V T} \frac{A_h}{\sum{A_h}} = \frac{\lambda_h A_h}{V T}.$$ This formula assumes that cameras are placed in each habitat type, although they do not need to be placed proportional to the habitat type availability, i.e., random sampling. Summing over all habitat-type abundances gives total abundance.

By using the EDE formula, we can scale the densities by the proportion of time spent in each habitat type, providing separate total abundance estimates for each habitat type, $$N = \frac{\lambda_h \sum{\phi_h}}{\phi_h} \frac{A_h}{V T} = \frac{\lambda_h A_h}{V T_h},$$ where $T_h = T \frac{\phi_h}{\sum{\phi_h}}$ is the habitat-specific sampling period. The issue with this method is that the errors change for each estimate depending on how much data are collected in each habitat type. To account for this, we can scale the full estimates by the proportion of cameras deployed in each habitat type to get camera-adjusted habitat abundances, $$N_h = \frac{\lambda_h \sum{\phi_h}}{\phi_h} \frac{A_h}{V T} \frac{C_h}{\sum{C_h}} = \frac{\lambda_h A_h}{V  T_h} \frac{C_h}{\sum{C_h}}.$$ Summing over this value gives total abundance. This last formula effectively estimates densities at each habitat type by accounting for the proportion of time spent in each habitat type and the proportion of cameras placed in each habitat type.

NOTE: These equations assume that the mean camera counts ($\lambda$) is calculated with all of the cameras in the data. A simpler way to write the formula is to assume that the mean estimates only use cameras in the habitat type. Then we can stop at the second equation.

##### Cameras Placed in One Habitat Type (Full-Bias Sample Design)

If we place all cameras on one habitat type, e.g., roads, then we can estimate total densities as $$\sum{d_h} = \frac{d_h \sum{\phi_h}}{\phi_h}.$$ $\phi_h$ for all $h$ may be estimated with GPS data or camera trap data, then all that is left to estimate is road density, $d_1$. We can do this with the same likelihood methods for estimating densities as the Poisson regression but with the sampling frame and sampling period adjusted to the size of the habitat type and the proportional time spent in the habitat type. For example, if the total sampling frame is 900 km$^2$ and the road habitat type is 10% of the total area, then the sampling frame for road density is $A_1 = 90 km^2$. Similarly, if the total sampling period is 1000 hours, then the sampling period for road density is adjusted to 15% of the total sampling period, or $T_1 = 150$. Combining all of this together, we can calculate total abundance with $$N = \frac{\lambda_1 \sum{\phi_1}}{\phi_1} \frac{A_1}{V T} = \frac{\lambda_1 A_1}{V T_1},$$ where $\lambda_1$ is the road density, and $V$ is the camera viewshed area NOTE:CHECK THIS MATH. NOT SURE IF DENSITY IS PROPERLY DEFINED

##### Cameras Non-randomly (Partial-Bias Sample Design)

If cameras are placed non-randomly but encounters are recorded in every habitat type, the above formula may be generalized to account to for the partial-bias camera placement. Camera-adjusted, habitat-specific abundances (abundances scale with camera proportions in habitat) are defined as $$N_h = \frac{\lambda_h \sum{\phi_h}}{\phi_h} \frac{A_h}{V T} \frac{C_h}{\sum{C_h}} = \frac{\lambda_h A_h}{V  T_h} \frac{C_h}{\sum{C_h}}$$ where $C_h$ is the number of cameras located in habitat $h$. Total abundance is calculated as the sum of all habitat type abundances, $\sum{N_h}$. CHECK

NOTE: Understand the difference between the full-bias design and partial-bias and why deconstructing the full design into weighted-camera abundances provides a better estimate. There is probably a better way to describe it other than weighted-camera abundance.

##### Estimating relative staying times

To use the formulas above, staying time must be estimated and can be done so with either gps collar data or camera traps. If camera traps are used, then cameras must be placed in every habitat type, which is not a requirement if staying time data are collected from collars.

Test these methods (staying time estimated with cameras vs gps)!

-   Compare these two with partial-bias sample designs. How much more accurate are the GPS models?

-   Compare the GPS-collected data with random, partial-bias, and full-bias sample designs. Do we get better precision if we place all cameras on one habitat type?
